#!/usr/bin/env tsx
/**
 * {{SERVER_NAME}} — {{DESCRIPTION}}
 *
 * MCP server scaffold (TypeScript, stdio transport).
 * Generated by mcp-forge.
 *
 * CRITICAL — five-name match (GUARD-003 from mcp-forge):
 *   The string `{{SERVER_NAME}}` must equal ALL of:
 *     1. plugin.json.name
 *     2. plugin.json.channels[].server  (channel plugins only)
 *     3. .mcp.json mcpServers.<key>
 *     4. new Server({ name: ... })      ← here
 *     5. any skill prefix mcp__plugin_<name>_<server>__<tool>
 *   Any mismatch silently breaks tool registration at install time.
 *
 * SPDX-License-Identifier: MIT
 */
import { Server } from '@modelcontextprotocol/sdk/server/index.js'
import { StdioServerTransport } from '@modelcontextprotocol/sdk/server/stdio.js'
import {
  CallToolRequestSchema,
  ListToolsRequestSchema,
} from '@modelcontextprotocol/sdk/types.js'
import { z } from 'zod'

// ---------------------------------------------------------------------------
// Server construction — name MUST match plugin.json and .mcp.json (GUARD-003)
// ---------------------------------------------------------------------------
const server = new Server(
  { name: '{{SERVER_NAME}}', version: '0.1.0' },
  {
    capabilities: {
      tools: {},
      // For channel plugins, also declare:
      //   'experimental/claude/channel': {},
      //   'experimental/claude/channel/permission': {},
    },
  }
)

// ---------------------------------------------------------------------------
// Tool: {{TOOL_NAME}} — example tool, replace with your own via /mcp-forge-tool
// ---------------------------------------------------------------------------
const {{TOOL_NAME}}Schema = z.object({
  message: z.string().describe('Text to echo back'),
})

const {{TOOL_NAME}}Tool = {
  name: '{{TOOL_NAME}}',
  description:
    'Example tool. Returns the input message in a structured envelope. ' +
    'Replace with your real tool via /mcp-forge-tool.',
  inputSchema: {
    type: 'object',
    properties: {
      message: { type: 'string', description: 'Text to echo back' },
    },
    required: ['message'],
  },
}

async function handle_{{TOOL_NAME}}(
  args: z.infer<typeof {{TOOL_NAME}}Schema>
): Promise<{ content: Array<{ type: string; text: string }>; isError?: boolean }> {
  const result = { ok: true, echo: args.message, at: new Date().toISOString() }
  return {
    content: [{ type: 'text', text: JSON.stringify(result, null, 2) }],
  }
}

// ---------------------------------------------------------------------------
// Request handlers
// ---------------------------------------------------------------------------
server.setRequestHandler(ListToolsRequestSchema, async () => ({
  tools: [{{TOOL_NAME}}Tool],
}))

server.setRequestHandler(CallToolRequestSchema, async (request) => {
  const { name, arguments: args } = request.params
  switch (name) {
    case '{{TOOL_NAME}}': {
      const parsed = {{TOOL_NAME}}Schema.safeParse(args ?? {})
      if (!parsed.success) {
        return {
          content: [{ type: 'text', text: `Schema error: ${parsed.error.message}` }],
          isError: true,
        }
      }
      return handle_{{TOOL_NAME}}(parsed.data)
    }
    default:
      return {
        content: [{ type: 'text', text: `Unknown tool: ${name}` }],
        isError: true,
      }
  }
})

// ---------------------------------------------------------------------------
// Boot
// ---------------------------------------------------------------------------
const transport = new StdioServerTransport()
await server.connect(transport)
