#!/usr/bin/env python3
"""
{{SERVER_NAME}} — {{DESCRIPTION}}

MCP server scaffold (Python, FastMCP over stdio).
Generated by mcp-forge.

CRITICAL — five-name match (GUARD-003 from mcp-forge):
  The string `{{SERVER_NAME}}` must equal ALL of:
    1. plugin.json.name
    2. plugin.json.channels[].server  (channel plugins only)
    3. .mcp.json mcpServers.<key>
    4. FastMCP(name=...)              <- here
    5. any skill prefix mcp__plugin_<name>_<server>__<tool>
  Any mismatch silently breaks tool registration at install time.

SPDX-License-Identifier: MIT
"""
from __future__ import annotations

from datetime import datetime, timezone
from typing import Any

from mcp.server.fastmcp import FastMCP

# ---------------------------------------------------------------------------
# Server construction — name MUST match plugin.json and .mcp.json (GUARD-003)
# ---------------------------------------------------------------------------
mcp = FastMCP("{{SERVER_NAME}}")


# ---------------------------------------------------------------------------
# Tool: {{TOOL_NAME}} — example tool, replace via /mcp-forge-tool
# ---------------------------------------------------------------------------
@mcp.tool()
async def {{TOOL_NAME}}(message: str) -> dict[str, Any]:
    """Example tool. Returns the input message in a structured envelope.

    Replace with your real tool via /mcp-forge-tool.

    Args:
        message: Text to echo back.

    Returns:
        Structured dict with ok/echo/at fields.
    """
    return {
        "ok": True,
        "echo": message,
        "at": datetime.now(timezone.utc).isoformat(),
    }


# ---------------------------------------------------------------------------
# Boot
# ---------------------------------------------------------------------------
if __name__ == "__main__":
    # stdio transport — do not switch to HTTP/SSE without a decision record
    mcp.run(transport="stdio")
